name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Utiliser HTTPS avec un token d'accès personnel
            cd ${{ secrets.PROJECT_PATH }}
            git config --global credential.helper cache
            git remote set-url origin https://${{ secrets.TOKEN }}@github.com/cedric-famibelle-pronzola/cedric-pronzola-v2.git
            
            # Reste du script de déploiement
            git pull origin master
            
            # Charger NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Vérifier la version de Node.js
            nvm use 22 || nvm install 22
            node -v
            
            # Installation de PM2 globalement si nécessaire
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            npm install
            npm run build
            
            # Utiliser le chemin complet vers PM2 si nécessaire
            $(npm bin -g)/pm2 restart ${{ secrets.PM2_APP_NAME }} || pm2 restart ${{ secrets.PM2_APP_NAME }}
